/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "./can/bsp_can.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_GRAPH_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_1    (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
#define ID_TIMER_UPDATE  (GUI_ID_USER + 0x10)
// 定义四个数据句柄
static GRAPH_DATA_Handle hGraphData1;
static GRAPH_DATA_Handle hGraphData2;
static GRAPH_DATA_Handle hGraphData3;
static GRAPH_DATA_Handle hGraphData4;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 7, 5, 227, 30, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 110, 240, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 4, 90, 80, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

/**
 * @brief 更新 Graph 控件上的电压值
 * @retval 无
 */
void UpdateGraph(void) {
    uint16_t voltage1 = Get_CAN_Voltage(1);  // 获取电压1（单位毫伏）
    uint16_t voltage2 = Get_CAN_Voltage(2);  // 获取电压2（单位毫伏）
    uint16_t voltage3 = Get_CAN_Voltage(3);  // 获取电压3（单位毫伏）
    uint16_t voltage4 = Get_CAN_Voltage(4);  // 获取电压4（单位毫伏）

    // 将毫伏转换为伏特
    float voltage1V = voltage1 / 100.0f;
    float voltage2V = voltage2 / 100.0f;
    float voltage3V = voltage3 / 100.0f;
    float voltage4V = voltage4 / 100.0f;

    // 为每条曲线添加新的电压值
    GRAPH_DATA_YT_AddValue(hGraphData1, voltage1V);
    GRAPH_DATA_YT_AddValue(hGraphData2, voltage2V);
    GRAPH_DATA_YT_AddValue(hGraphData3, voltage3V);
    GRAPH_DATA_YT_AddValue(hGraphData4, voltage4V);
}

/*********************************************************************
*
*       GRAPH_Voltage
*       用于初始化和配置电压图表(Graph)控件
*/
void GRAPH_Voltage(WM_HWIN hWin) {
    WM_HWIN hGraph;
    GRAPH_SCALE_Handle hScaleY;

    // 获取 Graph 控件句柄
    hGraph = WM_GetDialogItem(hWin, ID_GRAPH_0);

    // 配置 Graph 控件
    GRAPH_SetBorder(hGraph, 30, 5, 5, 35);  // 设置边框
    GRAPH_SetGridVis(hGraph, 1);  // 显示网格
    GRAPH_SetGridDistX(hGraph, 25);  // 设置 X 轴网格线间距为 25
    GRAPH_SetGridDistY(hGraph, 10);  // 设置 Y 轴网格线间距为 10
    GRAPH_SetLineStyleH(hGraph, GUI_LS_DOT);  // 设置横向网格为点状线

    // 创建 Y 轴刻度
    hScaleY = GRAPH_SCALE_Create(10, GUI_TA_LEFT, GRAPH_SCALE_CF_VERTICAL, 50);
    GRAPH_AttachScale(hGraph, hScaleY);
    GRAPH_SCALE_SetFont(hScaleY, GUI_FONT_13B_ASCII);
    GRAPH_SCALE_SetTextColor(hScaleY, GUI_RED);
    GRAPH_SCALE_SetFactor(hScaleY, 0.1);  // 设置Y轴刻度为10*0.1=1，即每个刻度代表1

    // 创建四条曲线数据对象
    hGraphData1 = GRAPH_DATA_YT_Create(GUI_GREEN, 100, NULL, 0);
    hGraphData2 = GRAPH_DATA_YT_Create(GUI_RED, 100, NULL, 0);
    hGraphData3 = GRAPH_DATA_YT_Create(GUI_BLUE, 100, NULL, 0);
    hGraphData4 = GRAPH_DATA_YT_Create(GUI_YELLOW, 100, NULL, 0);

    // 将曲线添加到 Graph 控件中
    GRAPH_AttachData(hGraph, hGraphData1);
    GRAPH_AttachData(hGraph, hGraphData2);
    GRAPH_AttachData(hGraph, hGraphData3);
    GRAPH_AttachData(hGraph, hGraphData4);

    // 创建并启动定时器，每 500ms 触发一次
    WM_CreateTimer(hWin, ID_TIMER_UPDATE, 500, 0);
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00B4E39D));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    TEXT_SetText(hItem, "Voltage Value:");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetText(hItem, "Graph:");
    // USER START (Optionally insert additional code for further widget initialization)
    
    // 调用 GRAPH_Voltage 函数初始化图表和定时器
    GRAPH_Voltage(pMsg->hWin);
	
  case WM_TIMER:
    // 检查定时器 ID
    if (WM_GetTimerId(pMsg->Data.v) == ID_TIMER_UPDATE) 
	{
      UpdateGraph();  // 更新 Graph 数据
      WM_RestartTimer(pMsg->Data.v, 500);
    }
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Voltage(void);
WM_HWIN Voltage(void) {
  WM_HWIN hWin;
  // 清空屏幕，避免显示旧的内容
  GUI_Clear();
  // 延时，确保显示更新
  GUI_Delay(10);
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
