/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "./can/bsp_can.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_GRAPH_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_1    (GUI_ID_USER + 0x03)


// USER START (Optionally insert additional defines)
#define ID_TIMER_UPDATE  (GUI_ID_USER + 0x10)
static GRAPH_DATA_Handle hGraphData;
static WM_HWIN hGraph;

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 7, 5, 227, 30, 0, 0x64, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 9, 110, 220, 210, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 4, 90, 80, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
/**
  * @brief 更新 Graph 控件上的电压值
  * @retval 无
  */
void UpdateGraph(void) {
    uint16_t voltage1 = Get_CAN_Voltage(1);
    uint16_t voltage2 = Get_CAN_Voltage(2);
    uint16_t voltage3 = Get_CAN_Voltage(3);
    uint16_t voltage4 = Get_CAN_Voltage(4);

    // 更新 Graph 数据，最多显示4个电压值
    GRAPH_DATA_YT_Clear(hGraphData);
    GRAPH_DATA_YT_AddValue(hGraphData, voltage1);
    GRAPH_DATA_YT_AddValue(hGraphData, voltage2);
    GRAPH_DATA_YT_AddValue(hGraphData, voltage3);
    GRAPH_DATA_YT_AddValue(hGraphData, voltage4);

}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  GRAPH_SCALE_Handle hScale;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00B4E39D));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    TEXT_SetText(hItem, "Voltage Value:");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetText(hItem, "Graph:");
    // USER START (Optionally insert additional code for further widget initialization)
    // 获取 Graph 控件句柄
    hGraph = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);

    // 配置 Graph 控件
    GRAPH_SetGridVis(hGraph, 1);  // 显示网格

    GRAPH_SetColor(hGraph, GUI_GREEN, GUI_GREEN);  // 曲线颜色
	
    // 创建数据句柄，最多存储4个点
    hGraphData = GRAPH_DATA_YT_Create(GUI_GREEN, 4, NULL, 0);
    GRAPH_AttachData(hGraph, hGraphData);

    // 设置 X 轴网格线间距为 25，保持不变
    GRAPH_SetGridDistX(hGraph, 25);

    // 设置 Y 轴网格线间距为 15
    GRAPH_SetGridDistY(hGraph, 10);

    // 设置网格线的显示样式为点状
    GRAPH_SetLineStyleH(hGraph, GUI_LS_DOT);  // 横向网格使用点状线
	
    // 设置 Y 轴大小
    GRAPH_SetVSizeY(hGraph, 15000);  // Y 轴最大值为 15000 mV
    GRAPH_SetVSizeX(hGraph, 4);  // X 轴显示4个点

    // 创建 X 轴刻度
    hScale = GRAPH_SCALE_Create(200, GUI_TA_HCENTER, GRAPH_SCALE_CF_HORIZONTAL, 50);

    GRAPH_AttachScale(hGraph, hScale);
    GRAPH_SCALE_SetFont(hScale, GUI_FONT_8_ASCII);

	
	// 创建并启动定时器，每 500ms 触发一次
    WM_CreateTimer(pMsg->hWin, ID_TIMER_UPDATE, 500, 0);
	break;

    case WM_TIMER:
    // 检查定时器 ID
    if (WM_GetTimerId(pMsg->Data.v) == ID_TIMER_UPDATE) {
      UpdateGraph();  // 更新 Graph
      WM_RestartTimer(pMsg->Data.v, 500);  // 重启定时器
    }
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Voltage(void);
WM_HWIN Voltage(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
